/*
 * 09.10.2023 Original version
 */


syntax = "proto3";
option java_multiple_files = true;

package dk.via.jpe.grpcplanets;

message DTOPlanet
{
  string name = 1;
  double distanceToTheSun = 2;
  double radius = 3;
}

message GetPlanetRequest
{
  string name = 1;
}

message GetPlanetResponse
{
  DTOPlanet planet = 1;
}

message GetPlanetsRequest
{
}

message GetPlanetsResponse
{
  repeated DTOPlanet planets = 1;
}

message DTOMoon
{
  string name = 1;
  int32 discovered = 2;
  string planet = 3;
}

message GetMoonRequest
{
  string name = 1;
}

message GetMoonResponse
{
  DTOMoon moon = 1;
}

message GetMoonsRequest
{
}

message GetMoonsResponse
{
  repeated DTOMoon moons = 1;
}

message GetAllMoonsForPlanetRequest
{
  string name = 1;
}

message GetAllMoonsForPlanetResponse
{
  repeated DTOMoon moons = 1;
}

service PlanetService
{
  rpc getPlanet( GetPlanetRequest ) returns ( GetPlanetResponse );
  rpc getPlanets( GetPlanetsRequest ) returns ( GetPlanetsResponse );

  rpc getMoon( GetMoonRequest ) returns ( GetMoonResponse );
  rpc getMoons( GetMoonsRequest ) returns ( GetMoonsResponse );

  rpc getAllMoonsForPlanet( GetAllMoonsForPlanetRequest ) returns ( GetAllMoonsForPlanetResponse );
}
