spring.application.name=SlaughterHouse

spring.datasource.url=jdbc:postgresql://localhost:5432/slaughterhouse
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=slaughterhouse

spring.grpc.server.port=9090
